---
image: code.ungleich.ch:5050/ungleich-public/cdist/cdist-ci:latest

stages:
    - test

before_script:
    - ./bin/cdist-build-helper version

shellcheck:
    stage: test
    script:
        - ./bin/cdist-build-helper shellcheck

pycodestyle:
    stage: test
    script:
        - ./bin/cdist-build-helper pycodestyle

unit_tests:
    stage: test
    script:
        - ./bin/cdist-build-helper test
